version: "3.3"
services:
  api:
    image: elites-bn-be
    container_name: elites_bn_be
    restart: always
    build: 
      context: ./
      args:
        - PORT=${PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_PORT_DEV=${DB_PORT_DEV}
      - DB_HOST_DEV=${DB_HOST_DEV}
      - NODE_ENV=development
      - DB_URL_DEV=${DB_URL_DEV}
    ports:
      - "3000:3000"
    volumes:
      - .:/elites-bn-be/
      - /elites-bn-be/src

  
  db:
    image: postgres:14-alpine
    restart: always
    env_file: 
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
    
    container_name: elites_db
volumes:
  database_data:
    driver: local

    
 

