version: "3.3"
services:
  app:
    restart: always
    build: ./
    links:
      - postgres

    # env_file: 
    #   - .env
    environment:
      # - DB_USERNAME_DEV=postgres
      # - DB_PASSWORD_DEV=admin123@
      # - DB_DATABASE_DEV=dev_barefoot_db
      # - DB_HOST_DEV=postgres
      # - DB_PORT_DEV=3000
      - DATABASE_URL=postgres://postgres:admin123@@postgres:5432/dev_barefoot_db
      # - NODE_ENV=development
      # - PORT=3000
      - PERSISTENCE_TYPE=postgres
    ports:
      - "5050:5050"
    volumes:
      - .:/elites-bn-be/
      - /elites-bn-be/node_modules

  
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      
       POSTGRES_PASSWORD: 'admin123@'
       POSTGRES_DB: 'dev_barefoot_db'
      
    volumes:
      - database_data:/var/lib/postgresql/data
    # env_file: .env
volumes:
  database_data:
    driver: local
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - 5050:3000
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=niyonzimadeus2002@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin123@
      
    
  #   env_file:
  #    - .env  

