version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: INSTALL DEPENDENCIES
          command: yarn install
      - run:
          name: RUN TEST
          command: yarn run test
      - run:
          name: UPLOAD COVERAGE
          command: yarn run coverage

workflows:
  test-deploy:
    jobs:
      - test