export const TRIP_CREATED = 'Trip request created successfully';
export const REQUEST_UPDATED = 'Trip request updated successfully';
export const FAILED_TRIP = 'Trip request failed';
export const NO_TRIP_FOUND = 'Trip Not Found';
export const TRIP_FOUND_MESSAGE = 'Trip Requests retrieved successfully ';
export const TRIP_DELETED_MESSAGE = 'Trip Requests deleted successfully ';
export const ERROR_DATES = 'ERROR: arrival date should be greater than departure date, departure date should not be in past!';
export const VALIDATION_ERROR = 'Error: Validation error';
export const REQUEST_APPROVED = 'Your trip request has been successfully approved';
